### PR TITLE
Use established connection if it exists

### PR DESCRIPTION
**Pull request by ldamman**

### CODE REVIEW

**Review by BrettRToomey — CHANGES_REQUESTED** [review]
It looks good, but I think we should respect the `retainConnection` attribute. 🙂

**Comment by ldamman** [comment]
@BrettRToomey currently the connection only gets set if retainConnection is flipped to true, but what if someone explicitly sets driver.connection to their own Connection object?  I'd think we'd want to respect that, especially since it's public.

Do we not want the user to be able to override the connection in the first place?  We could change the setter to private...

`public private(set) var connection: Connection?`

**Review by BrettRToomey — APPROVED** [review]

**Comment by BrettRToomey** [comment]
Oh, I simply misread the purpose of this. No matter what, a retained connection is required so there's no reason to check the attribute. Sorry!

**Comment by VolkerBb** [comment]
I'm currently writing an import task which uses up to six threads to import a big amount of data to the MySQL database via Fluent. I had the issue, that too many connections were opened and closed per second when not retaining the connection. Since my import procedure imports from different file streams at once which are up to 1GB of size each, I'm creating many objects of the same type at once and save them. I understand that the important thing of the unique connection is to grab the LAST_INSERT_ID, which – however – when using multiple threads to create objects of the same model class, could fail if two inserts are coming in via the same connection from different threads at the "same" time. 
My solution to this was to build a map where I store retained connections per Thread. I'd be happy if this could bring in a new idea to this discussion:

```
public class MySQLDriver: Fluent.Driver {
    public var idKey: String = "id"
    public var database: MySQL.Database
    
    /**
        Stores retained connections per Thread 
    */
    private var _connections:[Thread:Connection] = [:]
    
    /**
        Tells the driver wether or not to make a new database
        connection on every request.
        Keep this off if you want session variables to be retained.
        Setting it to `true` might cause timeout errors if there is no 
        activity during an extended period of time (MySQL default is 8hr).
     */
    public var retainConnection: Bool = false {
        didSet {
            if retainConnection == false {
                _connections = [:]
            }
        }
    }
    
    /**
        The active connection with the database, thread based.
    */
    public var connection: Connection? {
        set {
            _connections[Thread.current] = newValue
            retainConnection = true
        }
        get {
            return _connections[Thread.current]
        }
    }
    
    
    /**
      Returns either the thread based connection (if retainConnection is true) or a temporary connection
     */
    private func resolvedConnection() throws -> Connection {
        if retainConnection {
            if let conn = self.connection {
                return conn
            }
            let conn = try database.makeConnection()
            self.connection = conn
            return conn
        }
        return try database.makeConnection()
    }
```

In the query function I simply use this:

```   

        // create a reusable connection
        // so that LAST_INSERT_ID can be fetched
        let connection = try self.resolvedConnection()

```

**Comment by BrettRToomey** [comment]
@VolkerBb Currently, Fluent is undergoing a huge overhaul for the connection system. We're working on a connection pool where a thread can lock a connection down and then they can be reused when its done.

**Comment by tanner0101** [comment]
See https://github.com/vapor/fluent/pull/159

**Comment by tanner0101** [comment]
Closing this since https://github.com/vapor/fluent/pull/159 was merged.

**Pull request closed without merging**
